name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Plugins
          base: activity, community, repositories
          repositories_forks: yes
          repositories_affiliations: ""
          commits_authoring: wander4096@gmail.com
          plugin_languages: yes
          plugin_languages_ignored: html, css, js, renderscript
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_repositories: yes
